"""create course and section tables

Revision ID: e1a5b2a31977
Revises: 
Create Date: 2018-05-26 22:52:40.036650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1a5b2a31977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('activities', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('session', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('activity', sa.Text(), nullable=False),
    sa.Column('term', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('days', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_days'), 'sections', ['days'], unique=False)
    op.create_index(op.f('ix_sections_end'), 'sections', ['end'], unique=False)
    op.create_index(op.f('ix_sections_session'), 'sections', ['session'], unique=False)
    op.create_index(op.f('ix_sections_start'), 'sections', ['start'], unique=False)
    op.create_index(op.f('ix_sections_term'), 'sections', ['term'], unique=False)
    op.create_index(op.f('ix_sections_year'), 'sections', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_year'), table_name='sections')
    op.drop_index(op.f('ix_sections_term'), table_name='sections')
    op.drop_index(op.f('ix_sections_start'), table_name='sections')
    op.drop_index(op.f('ix_sections_session'), table_name='sections')
    op.drop_index(op.f('ix_sections_end'), table_name='sections')
    op.drop_index(op.f('ix_sections_days'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
